### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by newca12** [galarragas/spray-funnel#4]
Would be great to have this library in Maven Central

**Comment by jtjeferreira** [comment]
+1

**Comment by galarragas** [comment]
I'm publishing it to Bintray, much easier to handle for me and I would be forced to change the package name to `uk.co.pragmasoft.` to publish to maven central. Updated the documentation. 
You just have to replace the conjars related resolver with my bintray one (`resolvers += Resolver.bintrayRepo("galarragas", "maven")` )
