### ISSUE TITLE
Conflicting cross-version suffixes

### ISSUE THREAD

**Issue by AlexDibrivnyy** [galarragas/spray-funnel#8]
Hello,

I am trying to write application using your library but I have some problems with it. I can not add it to my project.

Used versions:
Scala version is: "2.11.2"
Akka: "2.3.5"
Spray: "1.3.1"

Firstly I tried to add library based on general [instruction.](https://github.com/galarragas/spray-funnel#adding-dependency-to-spray-funnel)
But it can not find version "1.0-spray1.3".

After that I tried the following version "1.0-RC3-spray1.3":

resolvers += "ConJars" at "http://conjars.org/repo"
libraryDependencies += "com.pragmasoft" %% "spray-funnel" % "1.0-RC3-spray1.3" 

And as result I received an error:

Error:[info] Loading project definition from /home/alexdibrivnyi/Documents/workspaces/workspace_bidpulse/bidpulse/BidPulse/project
[info] Set current project to bidpulse (in build file:/home/alexdibrivnyi/Documents/workspaces/workspace_bidpulse/bidpulse/BidPulse/)
[info] Defining *:artifactPath
[info] The new value will be used by no settings or tasks.
[info] Reapplying settings...
[info] Set current project to bidpulse (in build file:/home/alexdibrivnyi/Documents/workspaces/workspace_bidpulse/bidpulse/BidPulse/)
[info] Defining *:artifactClassifier
[info] The new value will be used by compile:packageBin::artifact, compile:packageDoc::artifact and 9 others.
[info]  Run `last` for details.
[info] Reapplying settings...
[info] Set current project to bidpulse (in build file:/home/alexdibrivnyi/Documents/workspaces/workspace_bidpulse/bidpulse/BidPulse/)
[info] Applying State transformations org.jetbrains.sbt.ReadProject from /home/alexdibrivnyi/.IdeaIC13/config/plugins/Scala/launcher/sbt-structure-0.13.jar
[info] Reading structure from /home/alexdibrivnyi/Documents/workspaces/workspace_bidpulse/bidpulse/BidPulse
[info] Updating {file:/home/alexdibrivnyi/Documents/workspaces/workspace_bidpulse/bidpulse/BidPulse/}bidpulse...
[info] Resolving org.scala-lang#scala-library;2.11.2 ...
[info] Resolving io.spray#spray-json_2.11;1.3.0 ...
[info] Resolving io.spray#spray-can_2.11;1.3.1 ...
[info] Resolving io.spray#spray-io_2.11;1.3.1 ...
[info] Resolving io.spray#spray-util_2.11;1.3.1 ...
[info] Resolving io.spray#spray-http_2.11;1.3.1 ...
[info] Resolving org.parboiled#parboiled-scala_2.11;1.1.6 ...
[info] Resolving org.parboiled#parboiled-core;1.1.6 ...
[info] Resolving io.spray#spray-routing_2.11;1.3.1 ...
[info] Resolving io.spray#spray-httpx_2.11;1.3.1 ...
[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.1 ...
[info] Resolving org.jvnet.mimepull#mimepull;1.9.4 ...
[info] Resolving com.chuusai#shapeless_2.11;1.2.4 ...
[info] Resolving com.typesafe.akka#akka-actor_2.11;2.3.5 ...
[info] Resolving com.typesafe#config;1.2.1 ...
[info] Resolving joda-time#joda-time;2.5 ...
[info] Resolving com.pragmasoft#spray-funnel_2.11;1.0-RC3-spray1.3 ...
[info] Resolving io.spray#spray-client;1.3.1 ...
[info] Resolving io.spray#spray-can;1.3.1 ...
[info] Resolving io.spray#spray-io;1.3.1 ...
[info] Resolving io.spray#spray-util;1.3.1 ...
[info] Resolving io.spray#spray-http;1.3.1 ...
[info] Resolving org.parboiled#parboiled-scala_2.10;1.1.6 ...
[info] Resolving io.spray#spray-httpx;1.3.1 ...
[info] Resolving com.typesafe.akka#akka-slf4j_2.11;2.3.2 ...
[info] Resolving org.slf4j#slf4j-api;1.7.5 ...
[info] Resolving commons-lang#commons-lang;2.2 ...
[info] Resolving io.spray#spray-testkit_2.11;1.3.1 ...
[info] Resolving com.typesafe.akka#akka-testkit_2.11;2.3.5 ...
[info] Resolving org.specs2#specs2-core_2.11;2.3.11 ...
[info] Resolving org.specs2#specs2-matcher_2.11;2.3.11 ...
[info] Resolving org.specs2#specs2-common_2.11;2.3.11 ...
[info] Resolving org.scalaz#scalaz-core_2.11;7.0.6 ...
[info] Resolving org.scala-lang.modules#scala-parser-combinators_2.11;1.0.1 ...
[info] Resolving org.scalaz#scalaz-concurrent_2.11;7.0.6 ...
[info] Resolving org.scalaz#scalaz-effect_2.11;7.0.6 ...
[info] Resolving org.scala-lang#scala-reflect;2.11.0 ...
[info] Resolving org.scalatest#scalatest_2.11;2.2.2 ...
[info] Resolving org.scala-lang#scala-reflect;2.11.2 ...
[info] Resolving org.scala-lang.modules#scala-xml_2.11;1.0.2 ...
[info] Resolving org.scala-lang#scala-compiler;2.11.2 ...
[info] Resolving org.scala-lang.modules#scala-parser-combinators_2.11;1.0.2 ...
[info] Resolving jline#jline;2.12 ...
[info] Resolving org.scoverage#scalac-scoverage-plugin_2.11;0.99.7 ...
[info] Resolving org.scala-lang#scala-library;2.11.1 ...
[info] Resolving commons-io#commons-io;2.4 ...
[info] Done updating.
[error] Modules were resolved with conflicting cross-version suffixes in {file:/home/alexdibrivnyi/Documents/workspaces/workspace_bidpulse/bidpulse/BidPulse/}bidpulse:
[error]    io.spray:spray-httpx _2.11, <none>
[error]    org.parboiled:parboiled-scala _2.11, _2.10
[error]    io.spray:spray-can _2.11, <none>
[error]    io.spray:spray-util _2.11, <none>
[error]    io.spray:spray-io _2.11, <none>
[error]    io.spray:spray-http _2.11, <none>
java.lang.RuntimeException: Conflicting cross-version suffixes in: io.spray:spray-httpx, org.parboiled:parboiled-scala, io.spray:spray-can, io.spray:spray-util, io.spray:spray-io, io.spray:spray-http
    at scala.sys.package$.error(package.scala:27)
    at sbt.ConflictWarning$.processCrossVersioned(ConflictWarning.scala:47)
    at sbt.ConflictWarning$.apply(ConflictWarning.scala:30)
    at sbt.Classpaths$$anonfun$60.apply(Defaults.scala:1090)
    at sbt.Classpaths$$anonfun$60.apply(Defaults.scala:1090)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
[error](*:update) Conflicting cross-version suffixes in: io.spray:spray-httpx, org.parboiled:parboiled-scala, io.spray:spray-can, io.spray:spray-util, io.spray:spray-io, io.spray:spray-http
[error] Modules were resolved with conflicting cross-version suffixes in {file:/home/alexdibrivnyi/Documents/workspaces/workspace_bidpulse/bidpulse/BidPulse/}bidpulse:
[error]    io.spray:spray-httpx _2.11, <none>
[error]    org.parboiled:parboiled-scala _2.11, _2.10
[error]    io.spray:spray-can _2.11, <none>
[error]    io.spray:spray-util _2.11, <none>
[error]    io.spray:spray-io _2.11, <none>
[error]    io.spray:spray-http _2.11, <none>
java.lang.RuntimeException: Conflicting cross-version suffixes in: io.spray:spray-httpx, org.parboiled:parboiled-scala, io.spray:spray-can, io.spray:spray-util, io.spray:spray-io, io.spray:spray-http
......

**Comment by soumyasd** [comment]
@galarragas - think you should update this in the documentation on the main page as well i.e., use 1.1-spray1.3 instead of 1.0-spray1.3

**Comment by galarragas** [comment]
Done :-)
